# Site settings
title: Travel Blog
email: aabhas@gmail.com
description: Amazing Travels.
baseurl: "/travel-blog"
twitter_username: aabhaschandra
avatar: "https://pbs.twimg.com/profile_images/592481405755469824/OCSmDaSt.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Aabhas Chandra" # Set default author name
      categories: "locations"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
